version: '3'
services:
  gateway-proxy:
    image: quay.io/solo-io/gloo-ee-envoy-wrapper:1.7.7
    entrypoint: ["envoy"]
    # command: ["-c", "/config/envoy.yaml", "--disable-hot-restart", "-l debug"]
    command: ["-c", "/config/envoy.yaml", "--disable-hot-restart"]
    volumes:
    - ./envoy-config.yaml:/config/envoy.yaml:ro
    ports:
    - "8090:8080"
    - "8443:8443"
    - "19000:19000"
    depends_on:
    - sds

  sds:
    image: quay.io/solo-io/sds:1.7.6
    volumes:
    - ./envoy-config.yaml:/config/envoy.yaml:ro
    ports:
    - "8234:8234"
    volumes:
    - ./gloo-mtls-certs:/etc/envoy/ssl:ro
    environment:
    - SDS_CLIENT=docker-compose-node
    - GLOO_MTLS_SDS_ENABLED=true
    - SDS_SERVER_ADDRESS=:8234

  #extauth:
  #  image: quay.io/solo-io/extauth-ee:1.4.6
  #  entrypoint: ["/bin/sh"]
  #  command: ["-c", "sleep 10 && /usr/local/bin/extauth"]
  #  environment:
  #  - SERVICE_NAME=ext-auth
  #  - GLOO_ADDRESS=gloo:9977
  #  - SERVER_PORT=8083
  #  - GLOO_LICENSE_KEY=$KEY_HERE
  #  - START_STATS_SERVER=true
  #  volumes:
  #  - "./data/auth-plugins:/auth-plugins:rw"
  #  ports:
  #  - "8083:8083"
  #  - "9092:9091"

  #ratelimit:
  #  image: quay.io/solo-io/rate-limit-ee:1.4.6
  #  environment:
  #  - GLOO_ADDRESS=gloo:9977
  #  - REDIS_URL=redis:6379
  #  - REDIS_SOCKET_TYPE=tcp
  #  - GLOO_LICENSE_KEY=$KEY_HERE
  #  ports:
  #  - "18081:18081"

  #redis:
  #  image: docker.io/redis:5
  #  environment:
  #  - MASTER=true
  #  ports:
  #  - "6379:6379"

  #petstore: # example application, the swagger petstore
  #  image: soloio/petstore-example:latest
  #  ports: 
  #  - "8090:8080"
  #  restart: always

