apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: gloo
    gloo: gloo
  name: gloo-xds
  namespace: gloo-system
spec:
  ports:
  - name: grpc-xds
    port: 9977
    protocol: TCP
    targetPort: 9977
  - name: rest-xds
    port: 9976
    protocol: TCP
    targetPort: 9976
  selector:
    gloo: gloo
  sessionAffinity: None
  type: LoadBalancer
