apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vm-petstore
  namespace: gloo-system
  labels:
    gateway: vm
spec:
  virtualHost:
    domains:
    - 'test'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: vm-petstore
            namespace: gloo-system
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: vm-petstore
  namespace: gloo-system
spec:
  static:
    hosts:
    - addr: petstore
      port: 8080

